emerald/urls.py
from django.conf.urls import url
from django.conf.urls import include

from django.contrib import admin

from emerald.views import index
from emerald.views import landing
from emerald.views import thanks

urlpatterns = [
        url(r'^admin/', admin.site.urls),
        url(r'^$', index, name='home'),
        url(r'^landing', landing, name='landing'),
        url(r'^thanks', thanks, name='thanks'),
        url(r'^accounts/', include('accounts.urls', namespace='accounts')),
        url(r'^contact/', include('contact.urls', namespace='contact')),
        url(r'^fbo/', include('fbo.urls', namespace='fbo')),
        url(r'^opportunity/', include('opportunity.urls', namespace='opportunity')),
        url(r'^userprofile/', include('userprofile.urls', namespace='userprofile')),
        url(r'^pipeline/', include('pipeline.urls', namespace='pipeline')),
]

fbo/urls.py
from django.conf.urls import url

from models import FboMaster

from views import FboDetailView, FboListView, FboMagicView, FboAddView

urlpatterns = [
        url(r'^(?P<pk>[0-9]*)/$', FboDetailView.as_view(), name='detail'),
        url(r'^list/$', FboListView.as_view(), name='list'),
        url(r'^magic/$', FboMagicView.as_view(), name='magic'),
        url(r'^add/(?P<pk>[0-9]*)/$', FboAddView, name='add'),
]

fbo/models.py
import datetime

from django.db import models

from accounts.models import Account
from contact.models import Contact
import choices
from managers import FboMasterManager 

class FboMaster(models.Model):

    solicitation_type = models.CharField(max_length=20, choices=choices.SOLICITATION_TYPES)
    date = models.DateField(null=True)
    zip_code = models.CharField(max_length=30, null=True) #zip
    class_code = models.CharField(max_length=10, null=True) #classcod
    naics = models.CharField(max_length=10, null=True)
    office_address = models.CharField(max_length=400, null=True) #offadd
    subject = models.CharField(max_length=400, null=True)
    solnbr = models.CharField(max_length=100, null=True)
    response_date = models.DateField(null=True) #respdate
    archive_date = models.DateField(null=True) #archdate
    contacts = models.ManyToManyField(Contact) #contact
    description = models.TextField() #desc
    link = models.URLField(null=True)
    email = models.EmailField(null=True)
    # links - array of links to documents
    # files - array of files
    agency = models.CharField(max_length=200, null=True)
    office = models.CharField(max_length=200, null=True)
    location = models.CharField(max_length=200, null=True)
    url = models.URLField()
    setaside = models.CharField(max_length=100, null=True)
    pop_country = models.CharField(max_length=50, null=True)
    pop_address = models.CharField(max_length=500, null=True)
    pop_zip = models.CharField(max_length=30, null=True)
    award_number = models.CharField(max_length=30, null=True)
    award_amount = models.IntegerField(null=True)
    award_date = models.DateField(null=True)
    line_number = models.CharField(max_length=30, null=True)
    ntype = models.CharField(max_length=30, null=True)


    objects = FboMasterManager()

    class Meta:

        verbose_name = 'solicitation'
        verbose_name_plural = 'solicitations'

    def __unicode__(self):

        return self.description

fbo/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class FboMasterFilterFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(FboMasterFilterFormHelper, self).__init__(*args, **kwargs)
        self.form_id = 'id-FboMasterForm'
        self.form_class = 'form'
        self.form_method = 'get'

        self.add_input(Submit('submit', 'Submit'))

fbo/views.py
from functools import partial

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template import RequestContext
from django.views.generic import View, DetailView, ListView

from emerald.views import FilteredSingleTableView
from filters import FboMasterFilter
from forms import FboMasterFilterFormHelper
from models import FboMaster
from opportunity.models import Opportunity
from tables import FboMasterTable

import pdb


class FboDetailView(LoginRequiredMixin, DetailView):

    model = FboMaster
    template_name = 'fbo/fbo-detail.html'

class FboListView(FilteredSingleTableView, LoginRequiredMixin, ListView):

    model = FboMaster
    template_name = 'fbo/fbo-list.html'
    table_class = FboMasterTable
    filter_class = FboMasterFilter
    helper_class = FboMasterFilterFormHelper

    # Necessary to set the row_attrs element

    def get_table(self, **kwargs):

        table = super(FboListView, self).get_table(**kwargs)
        table.row_attrs = self.get_row_attrs()
        return table

    def get_row_attrs(self):

        return {'class': self.get_watchlist_function()}

    def get_watchlist_function(self):

        ids = [opportunity.fbo_master.id for opportunity in Opportunity.objects.get_by_owner(self.request.user.userprofile)]
        test_fbo = FboMaster.objects.get(id='44058')
        return partial(self.in_watchlist, opportunity_ids=ids)

    def in_watchlist(self, fbo_record, opportunity_ids):

        if fbo_record.id in opportunity_ids:
            return 'watchlist'
        else:
            return ''

# Implements the magic view

class FboMagicView(FboListView):

    def get_context_data(self, **kwargs):
        context = super(FboMagicView, self).get_context_data(**kwargs)
        return context

    def get_table_data(self):
        qs = super(FboMagicView, self).get_table_data()
        if self.request.user.userprofile.sam:
            naics_list = self.request.user.userprofile.sam.naics.split()
            return qs.filter(naics__in=naics_list)
        else:
            messages.warning(self.request, 'Unable to filter solicitations without setting up your SAM record')
            return qs

def FboAddView(request, pk):

    # Get the information necessary to create a new opportunity

    opportunityFboMaster = FboMaster.objects.get(pk=pk)
    opportunityOwner = request.user.userprofile

    # Create the new opportunity

    newOpportunity = Opportunity.objects.create(fbo_master=opportunityFboMaster, owner=opportunityOwner)

    # Add contacts to the users's watchlist

    userprofile = request.user.userprofile
    for contact in opportunityFboMaster.contacts.all():
        contact.related_users.add(userprofile)

    # Go to the new opportunity record

    return HttpResponseRedirect(reverse('opportunity:detail', kwargs={'pk':newOpportunity.id}))

templates/fbo/btn-watch.html
<a href="{% url 'fbo:add' pk=record.pk %}"><button class="btn" type="button">Watch</button></a>

templates/fbo/fbo-detail.html
{% extends "emerald/base.html" %}

{% block content %}
    <div class="container">

		<!--The heading-->
		<h2>
			{{ object.subject }}
			<a href="{% url 'fbo:add' pk=object.pk %}">
				<button class="btn watchlist-btn">Watch</button>
			</a>
		</h2>

		<div class="object-detail">
			<h4>Solicitation Details</h4>
			<ul class="solicitation-info">
				<li>Solicitation Type: {{ object.get_solicitation_type_display }}</li>
				<li>Subject: {{ object.subject }}</li>
				<li>Agency: {{ object.agency }}</li>
				<li>Solicitation Number: {{ object.solnbr }}</li>
				<li>Setaside: {{ object.setaside }}</li>
			</ul>

			<h4>Contact Information</h4>
			<ul class="solicitation-contacts">
				{% for contact in object.contacts.all %}
					<li>{{ contact.name }}</li>
				{% endfor %}
			</ul>
		</div>

    <div>
{% endblock %}

templates/fbo/fbo-list.html
{% extends "emerald/base.html" %}
{% load django_tables2 crispy_forms_tags %}

{% block content %}
    <h2>FBO Solicitations</h2>
	<div class=container">
		{% render_table table 'emerald/filtered-table.html' %}
	</div>
{% endblock %}

templates/fbo/filtered-table.html
{% load django_tables2 %}
{% load i18n %}
{% load widget_tweaks %}

<div class="table-container">
{% block table %}
<form id="FboMasterForm" class="form" method="get">
<table{% if table.attrs %} {{ table.attrs.as_html }}{% endif %}>
    {% block table.thead %}
    {% if table.show_header %}
    <thead>
        <tr>
        {% for column in table.columns %}
            {% if column.orderable %}
            <th {{ column.attrs.th.as_html }}><a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header|title }}</a></th>
            {% else %}
            <th {{ column.attrs.th.as_html }}>{{ column.header|title }}</th>
            {% endif %}
        {% endfor %}
        </tr>
    </thead>
    {% endif %}
    {% endblock table.thead %}
    {% block table.tbody %}
    <tbody>
        <!--Here is the custom row for the filter-->

        <tr>
            <td>
                <button type="submit" class="btn btn-primary" value="submit"/>Filter</button>
            </td>
            {% for field in filter.form %}
            <td>
                {% render_field field class="form-control fbf-box" %}
            </td>
            {% endfor %}
        </tr>
        
        <!--End of custom row-->

        {% for row in table.page.object_list|default:table.rows %} {# support pagination #}
        {% block table.tbody.row %}
        <tr {{ row.attrs.as_html }}>
            {% for column, cell in row.items %}
                <td {{ column.attrs.td.as_html }}>{% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}</td>
            {% endfor %}
        </tr>
        {% endblock table.tbody.row %}
        {% empty %}
        {% if table.empty_text %}
        {% block table.tbody.empty_text %}
        <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
        {% endblock table.tbody.empty_text %}
        {% endif %}
        {% endfor %}
    </tbody>
    {% endblock table.tbody %}
    {% block table.tfoot %}
    {% if table.has_footer %}
    <tfoot>
        <tr>
        {% for column in table.columns %}
            <td>{{ column.footer }}</td>
        {% endfor %}
        </tr>
    </tfoot>
    {% endif %}
    {% endblock table.tfoot %}
</table>
</form>
{% endblock table %}

{% if table.page %}
{% with table.page.paginator.count as total %}
{% with table.page.object_list|length as count %}
{% block pagination %}
<ul class="pagination">
    {% if table.page.has_previous %}
        {% block pagination.previous %}
            <li class="previous">
                <a href="{% querystring table.prefixed_page_field=table.page.previous_page_number %}">{% trans "Previous" %}</a>
            </li>
        {% endblock pagination.previous %}
    {% endif %}

    {% if table.page.has_previous or table.page.has_next %}
        {% block pagination.current %}
            <li class="current">
                {% blocktrans with table.page.number as current and table.paginator.num_pages as total %}Page {{ current }} of {{ total }}{% endblocktrans %}
            </li>
        {% endblock pagination.current %}
    {% endif %}

    {% if table.page.has_next %}
        {% block pagination.next %}
            <li class="next">
                <a href="{% querystring table.prefixed_page_field=table.page.next_page_number %}">{% trans "Next" %}</a>
            </li>
        {% endblock pagination.next %}
    {% endif %}
    {% block pagination.cardinality %}
        <li class="cardinality">
            {% if total != count %}{% blocktrans %}{{ count }} of {{ total }}{% endblocktrans %}{% else %}{{ total }}{% endif %} {% if total == 1 %}{{ table.data.verbose_name }}{% else %}{{ table.data.verbose_name_plural }}{% endif %}
        </li>
    {% endblock pagination.cardinality %}
</ul>
{% endblock pagination %}
{% endwith %}
{% endwith %}
{% endif %}
</div>

templates/fbo/opportunity-list.html
{% extends "emerald/base.html" %}
{% load render_table from django_tables2 %}

{% block content %}
    <h2>FBO Watchlist</h2>
    <div>
        {% render_table table %}
    </div>
{% endblock %}