accounts/urls.py
from django.conf.urls import url

from views import register, LoginView, logout_view, AccountUpdate

urlpatterns = [
        url(r'^register/$', register, name='register'),
        url(r'login/$', LoginView.as_view(), name='login'),
        url(r'logout/$', logout_view, name='logout'),
        url(r'update/(?P<pk>[0-9]+)/$', AccountUpdate.as_view(), name='update'),
]

emerald/urls.py
from django.conf.urls import url
from django.conf.urls import include

from django.contrib import admin

from emerald.views import index
from emerald.views import landing
from emerald.views import thanks

urlpatterns = [
        url(r'^admin/', admin.site.urls),
        url(r'^$', index, name='home'),
        url(r'^landing', landing, name='landing'),
        url(r'^thanks', thanks, name='thanks'),
        url(r'^accounts/', include('accounts.urls', namespace='accounts')),
        url(r'^contact/', include('contact.urls', namespace='contact')),
        url(r'^fbo/', include('fbo.urls', namespace='fbo')),
        url(r'^opportunity/', include('opportunity.urls', namespace='opportunity')),
        url(r'^userprofile/', include('userprofile.urls', namespace='userprofile')),
        url(r'^pipeline/', include('pipeline.urls', namespace='pipeline')),
]

fbo/urls.py
from django.conf.urls import url

from models import FboMaster

from views import FboDetailView, FboListView, FboMagicView, FboAddView

urlpatterns = [
        url(r'^(?P<pk>[0-9]*)/$', FboDetailView.as_view(), name='detail'),
        url(r'^list/$', FboListView.as_view(), name='list'),
        url(r'^magic/$', FboMagicView.as_view(), name='magic'),
        url(r'^add/(?P<pk>[0-9]*)/$', FboAddView, name='add'),
]

pipeline/urls.py
from django.conf.urls import url

from models import Pipeline
from views import PipelineDetailView, PipelineDefaultNewView, PipelineManageView

urlpatterns = [
        url(r'^default-new/$', PipelineDefaultNewView, name='default-new'),
        url(r'^(?P<pk>[0-9]+)/$', PipelineDetailView.as_view(), name='detail'),
        url(r'^manage/$', PipelineManageView.as_view(), name='manage'),
]

pipeline/models.py
from __future__ import unicode_literals

from django.db import models
from django.dispatch import receiver

from userprofile.models import UserProfile

class Pipeline(models.Model):
    userprofile = models.ForeignKey(UserProfile)

    def __unicode__(self):
        return u'{0}\'s Pipeline'.format(self.userprofile.user.get_full_name())

class PipelineStage(models.Model):

    pipeline = models.ForeignKey(Pipeline)
    name = models.CharField(max_length=150)
    description = models.TextField(null=True)
    stage_number = models.IntegerField()

    def __unicode__(self):
        return u'{0}'.format(self.name)

emerald/views.py
from collections import OrderedDict

from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django_tables2 import SingleTableView

from accounts.forms import EmeraldGovRegistrationForm, LandingPageForm
from common.utils import mail_to_admin

import pdb

def index(request):
    return render(request, 'emerald/index.html')

def landing(request):
    form = LandingPageForm(data=request.POST or None)
    if request.method == 'POST' and form.is_valid():
        new_subscriber = form.save()
        mail_to_admin('New Email Subscriber', new_subscriber.email)
        return HttpResponseRedirect(reverse('thanks'))
    return render(request, 'emerald/landing.html', {
        'form': form
    })

def thanks(request):
    return render(request, 'emerald/thanks.html')

# Generic filtered table view

class FilteredSingleTableView(SingleTableView):
    filter_class = None

    def get_table_data(self):
        self.filter = self.filter_class(self.request.GET, queryset=super(FilteredSingleTableView, self).get_table_data())
        return self.filter.qs

    def get_context_data(self, **kwargs):
        context = super(FilteredSingleTableView, self).get_context_data(**kwargs)

        self.filter.form.helper = self.helper_class()

        table = context['table']

        # Make the filter form fields match the contents and order of the table columns

        column_headers = [column.name for column in table.columns]
        new_fields = OrderedDict()

        for column_name in column_headers:
            if column_name in self.filter.form.fields:
                new_fields[column_name] = self.filter.form.fields[column_name]

        self.filter.form.fields = new_fields
        context['filter'] = self.filter

        # Add an offset to tell the table how many columns the filter should be offset by

        if hasattr(table, 'offset'):
            context['offset_range'] = range(table.offset)
        # pdb.set_trace()

        return context

templates/emerald/base.html
<!DOCTYPE html>
<html>
<head>
	<meta name="google-site-verification" content="TyMetjaRala6rOgAN_mGddW_abSz-H2HTz23LG2Di3g" />

    <title>{% block title %} {% endblock %}</title>
	{% load staticfiles %}

	<link rel="icon" href="{% static 'emerald/images/emerald_icon.png' %}">

    <!-- Bootstrap  -->
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'emerald/css/custom.css' %}" />



	<!-- Google Analytics -->
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-92945208-1', 'auto');
	  ga('send', 'pageview');

	</script>

	{% block additional-sources %} {% endblock %}
</head>

<body>

	<!--Navbar-->

	<!--{% block navbar %}-->
	
	<!--<nav class="navbar navbar-light">-->
		<!--<a href="{% url 'home' %}" class="nabar-left navbar-brand"><img class="navbar-logo" src={% static 'emerald/images/Main_Logo_White.svg' %}></a>-->

	<!--{% endblock %}-->


    <!--Content-->

    {% block content %}

    {% endblock %}

    <!--Footer-->

    {% block footer %}
    {% endblock %}

<!-- jquery -->
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>

<!-- Latest compiled and minified JavaScript -->
<script 
  src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" 
  integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" 
  crossorigin="anonymous"></script>

<!-- Custom js --> <script src="{% static 'emerald/js/emerald.js' %}"></script>

</body>

</html>

templates/emerald/filtered-table.html
{% load django_tables2 %}
{% load i18n %}
{% load widget_tweaks %}

<div class="table-container">
{% block table %}
<form id="FboMasterForm" class="form" method="get">
<table{% if table.attrs %} {{ table.attrs.as_html }}{% endif %}>
    {% block table.thead %}
    {% if table.show_header %}
    <thead>
        <tr>
        {% for column in table.columns %}
            {% if column.orderable %}
            <th {{ column.attrs.th.as_html }}><a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header|title }}</a></th>
            {% else %}
            <th {{ column.attrs.th.as_html }}>{{ column.header|title }}</th>
            {% endif %}
        {% endfor %}
        </tr>
    </thead>
    {% endif %}
    {% endblock table.thead %}
    {% block table.tbody %}
    <tbody>
        <!--Here is the custom row for the filter-->

        <tr>
			<!--Offset the fitlter-->
			{% for i in offset_range %}
			<td></td>
			{% endfor %}

            {% for field in filter.form %}
            <td>
                {% render_field field class="form-control fbf-box" %}
            </td>
            {% endfor %}
        </tr>

		<tr>
            <td>
                <button type="submit" class="btn btn-primary" value="submit"/>Filter</button>
            </td>
		</tr>

        <!--End of custom row-->

        {% for row in table.page.object_list|default:table.rows %} {# support pagination #}
        {% block table.tbody.row %}
        <tr {{ row.attrs.as_html }}>
            {% for column, cell in row.items %}
                <td {{ column.attrs.td.as_html }}>{% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}</td>
            {% endfor %}
        </tr>
        {% endblock table.tbody.row %}
        {% empty %}
        {% if table.empty_text %}
        {% block table.tbody.empty_text %}
        <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
        {% endblock table.tbody.empty_text %}
        {% endif %}
        {% endfor %}
    </tbody>
    {% endblock table.tbody %}
    {% block table.tfoot %}
    {% if table.has_footer %}
    <tfoot>
        <tr>
        {% for column in table.columns %}
            <td>{{ column.footer }}</td>
        {% endfor %}
        </tr>
    </tfoot>
    {% endif %}
    {% endblock table.tfoot %}
</table>
</form>
{% endblock table %}

{% if table.page %}
{% with table.page.paginator.count as total %}
{% with table.page.object_list|length as count %}
{% block pagination %}
<ul class="pagination">
    {% if table.page.has_previous %}
        {% block pagination.previous %}
            <li class="previous">
                <a href="{% querystring table.prefixed_page_field=table.page.previous_page_number %}">{% trans "Previous" %}</a>
            </li>
        {% endblock pagination.previous %}
    {% endif %}

    {% if table.page.has_previous or table.page.has_next %}
        {% block pagination.current %}
            <li class="current">
                {% blocktrans with table.page.number as current and table.paginator.num_pages as total %}Page {{ current }} of {{ total }}{% endblocktrans %}
            </li>
        {% endblock pagination.current %}
    {% endif %}

    {% if table.page.has_next %}
        {% block pagination.next %}
            <li class="next">
                <a href="{% querystring table.prefixed_page_field=table.page.next_page_number %}">{% trans "Next" %}</a>
            </li>
        {% endblock pagination.next %}
    {% endif %}
    {% block pagination.cardinality %}
        <li class="cardinality">
            {% if total != count %}{% blocktrans %}{{ count }} of {{ total }}{% endblocktrans %}{% else %}{{ total }}{% endif %} {% if total == 1 %}{{ table.data.verbose_name|title }}{% else %}{{ table.data.verbose_name_plural|title }}{% endif %}
        </li>
    {% endblock pagination.cardinality %}
</ul>
{% endblock pagination %}
{% endwith %}
{% endwith %}
{% endif %}
</div>

templates/emerald/index.html
{% extends "emerald/base.html" %}

{% block title %}
    EmeraldGov - Home
{% endblock %}

{% block content %}
<a href={% url 'fbo:magic' %} class="btn btn-primary btn-lg" role=button" aria-pressed="true">Magic Search</a>
{% endblock %}

templates/emerald/landing-page-email-list.html
<!DOCTYPE html>
<html>

<head>

  {% load staticfiles %}

  <link rel="stylesheet" type="text/css" href="{% static 'emerald/style.css' %}" />
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

	<style>

			/* http://css-tricks.com/perfect-full-page-background-image/ */
			html {
				background: url({% static 'emerald/emerald-landing.svg' %}) no-repeat center center fixed; 
				-webkit-background-size: cover;
				-moz-background-size: cover;
				-o-background-size: cover;
				background-size: cover;
			}

			body {
				padding-top: 20px;
				font-size: 16px;
				font-family: "Open Sans",serif;
				background: transparent;
				color: white;
			}

			h1 {
				font-family: "Abel", Arial, sans-serif;
				font-weight: 400;
				font-size: 40px;
			}

			/* Override B3 .panel adding a subtly transparent background */
			.panel {
				background-color: rgba(255, 255, 255, 0.9);
			}

			.margin-base-vertical {
				margin: 40px 0;
			}

		</style>
  
</head>

<body>

<div class="container">
	<div class="row">
		<div class = "col-md-5 col-md-offset-3">
  
				<h1>Searching for Federal Goverment Opportunities?</h1>

				<p>Winning a federal government contract can be hard, especially if you don't know where to look to find the opportunity.</p>

				<p>EmeraldGov puts all of the FBO Opportunities base right at your fingertips in a clean and easy-to-use way</p>

				<form action="/mailing-list" method="post">
					<p class="input-group">
						<span class="input-group-addon">@</span>
						<input type="text" class="form-control input-lg" name="email" placeholder="noreply@example.com" />
					</p>
					<p class="help-block"><small>Enter your email and find opportunities today.</small></p>
					<p>
						<button type="submit" class="btn btn-success btn-lg">Submit</button>
					</p>
					</span>
				</form>

		</div>
	</div>
</div>

</body>

</html>

templates/emerald/landing.html
{% extends "emerald/base.html" %}
{% load staticfiles %}

{% block title %}
    EmeraldGov - Home
{% endblock %}

{% block additional-sources %}
	<link rel="stylesheet" type="text/css" href="{% static 'emerald/css/landing.css' %}" />
{% endblock %}

{% block login_info %}
{% endblock %}
{% block nav %}
{% endblock %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="logo-header col-md-12">
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 text-center">
			<img id="logo" class="center" src="static/emerald/images/emerald-logo.png">
		</div>
	</div>
	<div class="row">
		<div class="header text-center">
			<h1 class="header">Win More Business</h1>
		</div>
		<p class="sub-header text-muted text-center">
			Use EmeraldGov to find and win government contracts.
		</p>
	</div>
	<div class="row">
		<div class="col-md-4 col-md-offset-4 text-center">
			<form action="#" method="post">{% csrf_token %}
				{{ form }}
			<div class="form-action">
				<button type="submit" class="btn btn-lg text-center" value="Get Started">Get Free Beta Invite</button>
			</div>
			</form>
		</div>
	</div>

	<!--Feature Descriptions-->

	<!--<div class="row">-->
		<!--<div class="row">-->
			<!--<div class="col-md-2 col-md-offset-2 text-center">-->
				<!--<h2>Solicitaton Database</h2>-->
				<!--<div class="feature-desc">-->
					<!--<p>-->
						<!--Search a database of all the solicitations on fbo.gov, -->
					<!--</p>-->
				<!--</div>-->
			<!--</div>-->
			<!--<div class="col-md-2 col-md-offset-1 text-center">-->
				<!--<h2>Magic</br> Search</h2>-->
				<!--<div class="feature-desc">-->
					<!--<p>-->
						<!--Sifting through the never-ending torrent of opportunities takes up way too much of your time.  EmeraldGov's "Magic Search" feature uses your Cage Code to find all of the most relevant opportunities so that you can spend more time capturing and fulfilling contracts, and less time looking for them.-->
					<!--</p>-->
				<!--</div>-->
			<!--</div>-->
			<!--<div class="col-md-2 col-md-offset-1 text-center">-->
				<!--<h2>Contact Management</h2>-->
				<!--<div class="feature-desc p-1">-->
					<!--<p>-->
						<!--EmeraldGov understands that government contracting is all about relationships, so our platform gives you all of the tools you need to build productive relationships with the key government buyers in your industry.-->
					<!--</p>-->
				<!--</div>-->
			<!--</div>-->
		<!--</div>-->
	<!--</div>-->

	<div class="row">
		<div class="col-md-4 col-md-offset-4 text-center">
			<p class="beta-notification">EmeraldGov is getting ready to launch, but before we do we are inviting people to try us out for free during our beta test! Enter your email address to get free early access to this new technology, and take your business to the next level.</p>
		</div>
	</div>
</div>
{% endblock %}

templates/emerald/silver.html
<!DOCTYPE html>
<html>
<head>
	<meta name="google-site-verification" content="TyMetjaRala6rOgAN_mGddW_abSz-H2HTz23LG2Di3g" />

    <title>{% block title %} {% endblock %}</title>
	{% load staticfiles %}

	<link rel="icon" href="{% static 'emerald/images/emerald_icon.png' %}">

    <!-- Bootstrap  -->
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'emerald/css/custom.css' %}" />



	<!-- Google Analytics -->
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-92945208-1', 'auto');
	  ga('send', 'pageview');

	</script>

	{% block additional-sources %} {% endblock %}
</head>

<body>

    <!--Navbar-->

    <nav class="navbar navbar-light navbar-default">
		{% block login_info %}

			<!--If the user is logged in , show their username and a logout button-->

			{% if request.user.is_authenticated %}

				<span class="navbar-right">
					<p class="navbar-text">Welcome, <a href="{% url 'userprofile:update' user.userprofile.id|default_if_none:0 %}">{{ user.first_name }}</a></p>
					<a href="{% url 'accounts:logout' %}">
						<button class="btn btn-primary navbar-btn" type="button">
							Sign Out
						</button>
					</a>
				</span>

			<!--Else, show a login button-->

			{% else %}

				<a href="{% url 'accounts:login' %}">
					<button class="btn btn-primary navbar-btn navbar-right" type="button">
						Sign In
					</button>
				</a>

			{% endif %}

		{% endblock %}
		{% block nav %}
		<a class="navbar-brand" href="#">EmeraldGov</a>
		<ul class="nav navbar-nav">
			<li class="nav-item home">
				<a class="nav-link" id="link-green" href="{% url 'home' %}">Home</a>
			</li>
			<li class="nav-item fbo">
				<a class="nav-link" href="{% url 'fbo:list' %}">Search</a>
			</li>
			<li class="nav-item opportunity">
				<a class="nav-link" href="{% url 'opportunity:list' %}">Watchlist</a>
			</li>
			<li class="nav-item pipeline">
				<a class="nav-link" href="
				{% if request.user.userprofile.pipeline_set.first %}
				{% url 'pipeline:detail' pk=request.user.userprofile.pipeline_set.first.pk %}
				{% else %}
				{% url 'pipeline:default-new' %}
				{% endif %}
				">Pipeline</a>
			</li>
			<li class="nav-item contact">
				<a class="nav-link" href="{% url 'contact:list' %}">Contacts</a>
			</li>
		</ul>
		{% endblock %}
    </nav>

	<!-- Messages -->

	{% if messages %}
        {% for message in messages %}
			<div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
	{% endif %}

    <!--Content-->

    {% block content %}

    {% endblock %}

    <!--Footer-->

    {% block footer %}
    {% endblock %}

<!-- jquery -->
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<!-- Custom js --> <script src="{% static 'emerald/js/emerald.js' %}"></script>

</body>

</html>

templates/emerald/thanks.html
{% extends "emerald/base.html" %}
{% load staticfiles %}

{% block title %}
	Thank You
{% endblock %}

{% block additional-sources %}
	<link rel="stylesheet" type="text/css" href="{% static 'emerald/css/thanks.css' %}" />
{% endblock %}

{% block login_info %}
{% endblock %}
{% block nav %}
{% endblock %}

{% block content %}
	<div class="container-fluid">
		<div class="jumbotron text-xs text-center">
			<h1 class="display-3">Thank You!</h1>
			Thank you for signing up for out beta test! We're very excited to have you involved.  We will send you an email invitation as soon as the software is ready to use.  In the meantime we'll send you an email or two to get you input on what could make this software great.  We want to know what you need, so we can build it for you.  We look forward to hearing from you!
		</div>
		<div class="text-center">
			<img id="logo" src="static/emerald/images/emerald-logo.png">
		</div>
	</div>
{% endblock %}

templates/emerald/zygarde.html
{% extends "emerald/base.html" %}
{% load staticfiles %}

{% block title %}
    EmeraldGov - Home
{% endblock %}

{% block additional-sources %}
	<link rel="stylesheet" type="text/css" href="{% static 'emerald/css/zygarde.css' %}" />
{% endblock %}

{% block login_info %}
{% endblock %}
{% block nav %}
{% endblock %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12 text-center">
			<img id="logo" class="center" src="static/emerald/images/emerald-logo.png">
		</div>
	</div>
	<div class="row">
		<div class="header text-center">
			<h1 class="header">Win More Business</h1>
		</div>
		<p class="sub-header text-muted text-center">
			Use EmeraldGov to find and win government contracts.
		</p>
	</div>
	<div class="row">
		<div class="col-md-4 col-md-offset-4 text-center">
			<form action="#" method="post">{% csrf_token %}
				{{ form }}
			<div class="form-action">
				<button type="submit" class="btn btn-lg text-center" value="Get Started">Get Free Beta Invite</button>
			</div>
			</form>
		</div>
	</div>

	<!--Feature Descriptions-->

	<!--<div class="row">-->
		<!--<div class="row">-->
			<!--<div class="col-md-2 col-md-offset-2 text-center">-->
				<!--<h2>Solicitaton Database</h2>-->
				<!--<div class="feature-desc">-->
					<!--<p>-->
						<!--Search a database of all the solicitations on fbo.gov, -->
					<!--</p>-->
				<!--</div>-->
			<!--</div>-->
			<!--<div class="col-md-2 col-md-offset-1 text-center">-->
				<!--<h2>Magic</br> Search</h2>-->
				<!--<div class="feature-desc">-->
					<!--<p>-->
						<!--Sifting through the never-ending torrent of opportunities takes up way too much of your time.  EmeraldGov's "Magic Search" feature uses your Cage Code to find all of the most relevant opportunities so that you can spend more time capturing and fulfilling contracts, and less time looking for them.-->
					<!--</p>-->
				<!--</div>-->
			<!--</div>-->
			<!--<div class="col-md-2 col-md-offset-1 text-center">-->
				<!--<h2>Contact Management</h2>-->
				<!--<div class="feature-desc p-1">-->
					<!--<p>-->
						<!--EmeraldGov understands that government contracting is all about relationships, so our platform gives you all of the tools you need to build productive relationships with the key government buyers in your industry.-->
					<!--</p>-->
				<!--</div>-->
			<!--</div>-->
		<!--</div>-->
	<!--</div>-->

	<div class="row">
		<div class="col-md-4 col-md-offset-4 text-center">
			<p class="beta-notification">EmeraldGov is getting ready to launch, but before we do we are inviting people to try us out for free during our beta test! Enter your email address to get free early access to this new technology, and take your business to the next level.</p>
		</div>
	</div>
</div>
{% endblock %}